options:
  prev_tag: "versio-prev"

projects:
  - name: "guitos"
    id: 1
    tag_prefix: ""
    labels: npm
    version:
      file: "package.json"
      json: "version"

sizes:
  use_angular: true
  fail: ["*"]
