name: Install dependencies
description: Installs dependencies
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # ratchet:pnpm/action-setup@v4
      with:
        version: 9.4.0

    - name: Setup Node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # ratchet:actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Audit dependencies
      shell: bash
      run: pnpm audit --audit-level=moderate
