name: Run e2e tests
description: Runs playwright tests
runs:
  using: "composite"
  steps:
    - name: Run Playwright tests
      shell: bash
      run: pnpm exec playwright test
      env:
        HOME: /root

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
