name: PR
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: test
    timeout-minutes: 5
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.63.0@sha256:eff16c30e6f3f4af0a03fa4b706120d5e9b0891c344a27d64559aff5900a4a27 # ratchet:mcr.microsoft.com/playwright:v1.63.0
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/deps
        name: Install
      - uses: ./.github/actions/test
        name: Test
      - uses: ./.github/actions/playwright
        name: Test e2e
