name: PR
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: test
    timeout-minutes: 5
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1@sha256:b0ab6f3cb99aa7803adbc14d9027ec1785fc6e433b97e134e0f8fe61683b6b53 # ratchet:mcr.microsoft.com/playwright:v1.59.1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/deps
        name: Install
      - uses: ./.github/actions/test
        name: Test
      - uses: ./.github/actions/playwright
        name: Test e2e
