name: PR
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: test
    timeout-minutes: 5
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.1@sha256:9bd26ad900bb5e0f4dee75839e957a89ae89c2b7ab1e76050e559790e946b948 # ratchet:mcr.microsoft.com/playwright:v1.61.1
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ./.github/actions/deps
        name: Install
      - uses: ./.github/actions/test
        name: Test
      - uses: ./.github/actions/playwright
        name: Test e2e
